name: good

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04 # конкретная версия

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run:
          npm ci  # использование npm ci для чистой установки зависимостей

      - name: Run tests
        run: 
          npm test  # тесты должны завершиться успешно, иначе пайплайн остановится
