name: good

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04 # конкретная версия
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm  # Кэшируем npm глобальный кеш
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Check for package-lock.json
        id: check_lockfile
        run: |
          if [ -f package-lock.json ]; then
            echo "lockfile=true" >> $GITHUB_ENV
          else
            echo "lockfile=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies (with or without lockfile)
        run: |
          if [ "${{ env.lockfile }}" = "true" ]; then
            echo "Using npm ci for clean install..."
            npm ci
          else
            echo "package-lock.json not found, using npm install..."
            npm install
          fi

      - name: Run tests
        run: npm test
